;;; emacs-parquet-explorer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from emacs-parquet-explorer.el

(autoload 'emacs-parquet-explorer-open "emacs-parquet-explorer" "\
Open FILE in an interactive GPU-accelerated Parquet data viewer buffer.

(fn FILE)" t)
(register-definition-prefixes "emacs-parquet-explorer" '("emacs-parquet-explorer--run-export"))

;;; End of scraped data

(provide 'emacs-parquet-explorer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacs-parquet-explorer-autoloads.el ends here
